name: heldis
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  animate_icons: ^2.0.0
  auto_route: ^3.2.2
  cloud_firestore: ^3.1.6
  cupertino_icons: ^1.0.2
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.2.0
  flutter_native_splash: ^2.0.2
  flutter_riverpod: ^1.0.3
  google_fonts: ^2.2.0
  grouped_list: ^4.2.0
  hooks_riverpod: ^1.0.3
  line_icons: ^2.0.1
  lottie: ^1.2.1
  qr: ^3.0.0
  supercharged: ^2.1.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
assets:
  - assets/
  - assets/images
